### ISSUE TITLE
Cache Python AppImage when building Apps

### ISSUE THREAD

**Issue by niess** [niess/python-appimage#12]
Add a caching of base Python AppImages when building Apps. In order to avoid downloading from GitHub each time.

**Comment by niess** [comment]
@srevinsaju I added the possibility to install from a downloaded Python AppImage with the `-b` option. For example:

```bash
python-appimage build app /path/to/guiscrcpy/appimage \
                          -b python3.8.2-cp38-cp38-manylinux1_x86_64.AppImage
```

The base Python AppImage must be executable.

Adding your feature request would require a bit more work. I keep it here as an issue for the record.

**Comment by srevinsaju** [comment]
@niess, is this functionality already added to master ?

**Comment by niess** [comment]
@srevinsaju sorry, I didn't see your message up to now. The caching is not yet implemented. This issue is just a reminder. However, the option to build from an existing PythonAppimage, available on disk, has been implemented and is available in the latest release.

**Comment by srevinsaju** [comment]
thanks
