### ISSUE TITLE
Would it be possible to include pyyaml in the appimage?

### ISSUE THREAD

**Issue by mjtueros** [niess/python-appimage#13]
it is used by the astropy hdf5 interface, and i need it to trun the ZHAireS HDF5 file format.

**Comment by niess** [comment]
Matias,

you can add it to the extracted image using pip. For example as:

```bash
./python3-x86_64.AppImage --appimage-extract
ln -s ./squashfs-root/AppRun python3
./python3 -m pip install pyyaml
```

If you want to rebuild the modified Python as an AppImage you can use [appimagetool](https://appimage.github.io/appimagetool). For example:

```bash
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool-x86_64.AppImage
./appimagetool-x86_64.AppImage -n squashfs-root python3-x86_64.AppImage
rm -rf squashfs-root python3
```

**Comment by mjtueros** [comment]
Hi Valentin.
Thanks for your answer. Woudlnt it be possible to put it in the "official"
python appimage?. I have already solved it on my side.
But my point was most to the fact that  people will be using my HDF5 files
for a while, and it makes
little sense to have them to have 2 different Appimages, one with and one
without YAML

Cheers
Matias

**Comment by niess** [comment]
Hello Matias,

this is confusing indeed. There are many Python AppImages now.

Could we say that the official one for GRAND is [grand-mother/python](https://github.com/grand-mother/python), as it was previously the case. I gave you access rights over it. If you need to add something you can just edit the [requirements.txt](https://github.com/grand-mother/python/blob/master/appimage/requirements.txt), e.g. using the web interface. Note that rebuilding the image takes ~2 min. You can monitor the status by looking at the [GitHub actions](https://github.com/grand-mother/python/actions) of the repo.

I already added `pyyaml`. I also added the `grand` package and for @grand-oma I added IPython as well. You can enable the latter by running: `./grand-python-x86_64.AppImage - m IPython`.
