### ISSUE TITLE
AppRun: shebang customization

### ISSUE THREAD

**Issue by anki-code** [niess/python-appimage#14]
Hi @niess! Thank you for your work!

I've found that #8 appears because xonsh was running in not interactive bash mode.

If AppRun shebang will be `#! /bin/bash -i` instead of `#! /bin/bash` the xonsh will work perfect :)

I've made the [fix for my build](https://github.com/xxh/xonsh-appimage/blob/master/build.sh#L6) and just want to let you know.

It will be cool if there will be an option to AppRun shebang customization.

Thanks!

**Comment by niess** [comment]
@anki-code Great that you found the origin of this problem and that it is easy to fix :)

concerning the shebang customization I could mirror the one of the `entrypoint.sh` if any is provided.

**Comment by anki-code** [comment]
>  I could mirror the one of the entrypoint.sh if any is provided.

I don't clearly understand what you mean.

**Comment by niess** [comment]
The idea is the following. If the `entrypoint.sh` script has a shebang in the 1st line then it is used in `AppRun` as well, including its option(s) e.g. `-i`. Otherwise the current default shebang is used. This is to avoid adding yet another CLI option.

**Comment by anki-code** [comment]
It will be great!
