### ISSUE TITLE
tk and tcl path

### ISSUE THREAD

**Issue by mortenee** [niess/python-appimage#15]
After updating to a newer release my tkinter app no longer worked. 
Fixed it by changing these lines in AppRun:
export TCL_LIBRARY="${APPDIR}/usr/share/tcltk/tcltcl-version"
export TK_LIBRARY="${APPDIR}/usr/share/tcltk/tktk-version"
to this:
export TCL_LIBRARY="${APPDIR}/usr/share/tcltk/tcl8.5"
export TK_LIBRARY="${APPDIR}/usr/share/tcltk/tk8.5"

Tested with python3.8.2-cp38-cp38-manylinux2014_x86_64.AppImage

Everything else works great. Thanks a lot for doing this :)

**Comment by niess** [comment]
@mortenee Thank you for reporting this bug. It should be patched now with the current release. Sorry, about this. I started some modifications and apparently I stopped in the middle :(

I would definitively need some test suite.

**Comment by mortenee** [comment]
Works now :)
