### ISSUE TITLE
tcltk-env: command not found

### ISSUE THREAD

**Issue by anki-code** [niess/python-appimage#17]
Hi! Thank you for your work!

Looks like after 5552c1f7cb5aa71b54deeb6ddf9578a81bfd61b8 I get 
```
/tmp/.mount_xonsh-ifYiMy/AppRun: line 7: tcltk-env: command not found
```
When run `xonsh.AppImage`.

**Comment by niess** [comment]
@anki-code sorry. It should be patched now.
Also I added the shebang mirroring as discussed.

**Comment by anki-code** [comment]
The error has gone and new shebang works like a charm! Hurray! 🎉 🎉 🎉 
Thanks!
