### ISSUE TITLE
SSL CERTFILE commit breaks new appimages

### ISSUE THREAD

**Issue by srevinsaju** [niess/python-appimage#26]
running an appimage built using `python-appimage` fails with the following error:
```
/tmp/appimage_extracted_ff11d2f4ca2d1e1dbfa7e9958e75c7e0/AppRun: line 12: cert-file: command not found
```

This is how my AppRun looks like 
```
#! /bin/bash

# Export APPRUN if running from an extracted image
self="$(readlink -f -- $0)"
here="${self%/*}"
APPDIR="${APPDIR:-${here}}"

# Export TCl/Tk
export TCL_LIBRARY="${APPDIR}/usr/share/tcltk/tcl8.4"
export TK_LIBRARY="${APPDIR}/usr/share/tcltk/tk8.4"
export TKPATH="${TK_LIBRARY}"
cert-file

# Call the entry point
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
export ZAP="TRUE"

${APPDIR}/usr/bin/python3.8 -s ${APPDIR}/opt/python3.8/bin/zap "$@"
```

I am not sure why the `cert-file` popped in. Maybe it was not formatted correctly?

**Comment by niess** [comment]
@srevinsaju This should be fixed now. Sorry for the inconvenience. This was due to my last patch not being forwarded to the applications builder. CI tests only check that the application builds but not that it works :( Hence this wasn't spotted earlier.

**Comment by srevinsaju** [comment]
ok, thanks! I will take a look now

**Comment by srevinsaju** [comment]
The new tests looks like an improvement :tada: Nice!!

**Comment by niess** [comment]
Yes, hopefully this will prevent such issues in the future

**Comment by srevinsaju** [comment]
Tested. Error does not occur now :tada:

**Comment by niess** [comment]
Great :)
