### ISSUE TITLE
Does it include Tkinter? (Python's standard GUI)

### ISSUE THREAD

**Issue by Symbian9** [niess/python-appimage#4]
As *Tkinter* is *Python's de facto standard GUI*, and always bundled in Python distributions for MS Windows, I expect it should be bundled inside this AppImage

- https://en.wikipedia.org/wiki/Tkinter

Think, it may require also bundle *Tcl/Tk* inside *this AppImage* too, as not all Linux now distributed with Tcl/Tk.

**Comment by niess** [comment]
@Symbian9 Yes `tkinter` is bundled as well as its deps: `libtcl`, `libtk` and their data (`under usr/share/tcltk`). For example, with a python3 AppImage, you can try:

```python3
from tkinter import Tk
Tk()
```
Note that depending on the manylinux tag (`1`, `2010` or `2014`) different versions of Tcl/Tk are bundled (`8.4` or `8.5`).
