### ISSUE TITLE
{install,build,which} response

### ISSUE THREAD

**Issue by T897T** [niess/python-appimage#56]
I was told to ask here:
I have no idea what to input into the terminal after, no I don't know linux at all. I'm just trying to get python working on my chromebook.
tylonsecret@penguin:~$` python3 python_appimage-1.2.1-py2.py3-none-any/python_appimage/__main__.py
usage: python-appimage [-h] [-q] [-v] {install,build,which} ...

Bundle a Python installation into an AppImage

optional arguments:
  -h, --help            show this help message and exit
  -q, --quiet           disable logging
  -v, --verbose         print extra information

command:
  {install,build,which}
                        Command to execute

**Comment by niess** [comment]
Hello @T897T ,

I never tried Python AppImages on a chromebook. If this is an x86_64 Linux, then you could  follow the [basic installation](https://python-appimage.readthedocs.io/en/latest/#basic-installation) documentation and see if it works? That is, in a term run

```
wget https://github.com/niess/python-appimage/releases/download/python3.11/python3.11.0-cp311-cp311-manylinux2014_x86_64.AppImage

chmod +x python3.11.0-cp311-cp311-manylinux2014_x86_64.AppImage

./python3.11.0-cp311-cp311-manylinux2014_x86_64.AppImage

```
the last command line should run the Python AppImage.

(P.S.: you are trying to run the `python-appimage` utility instead, which is meant for building Python AppImages and Python based app. But ready to use Python AppImages are already available for download).
