### ISSUE TITLE
Why do the old Python versions get rebuilt so often?

### ISSUE THREAD

**Issue by probonopd** [niess/python-appimage#6]
Hi @niess, thank you for this _extremely_ useful project, highly appreciated. :+1: 
Brilliant idea to extract the manylinx Python from the official Docker container, hats off!

Just a question, why do the old Python versions get rebuilt so often? Isn't it a little wasteful?

**Comment by niess** [comment]
Thank you :)

This is indeed not optimal :( Ideally I would rebuild the Python AppImage whenever the docker image changes. But I don't know a way to trigger that on GitHub workflows. So for now I am rebuilding the images periodically using a cron trigger. This is specified [here](https://github.com/niess/python-appimage/blob/master/.github/workflows/appimage.yml#L8).

Maybe, the job could detect if the trigger is cron (i.e. periodical) and then only build the AppImage  if the Docker image has changed. If there is a way to check this pro-actively?

**Comment by probonopd** [comment]
I don*t know how to do this, but maybe once a month would be sufficient?

**Comment by niess** [comment]
Indeed. I decreased the update frequency to weekly. Anyway, one can trigger this manually if needed.
