### ISSUE TITLE
how can use this and linuxdeploy to build appimage

### ISSUE THREAD

**Issue by newyorkthink** [niess/python-appimage#67]
can you write tutorial

**Comment by niess** [comment]
Hello @newyorkthink ,

I actually never used both projects simultaneously, only separately. My guess was that one could use one of the extracted Python Appimages as input AppDir to linuxdeploy.

I someone has been successful in doing so, I would be glad to add its directives to the documentation, for e.g. as a PR?

**Comment by newyorkthink** [comment]
> Hello @newyorkthink ,
> 
> I actually never used both projects simultaneously, only separately. My guess was that one could use one of the extracted Python Appimages as input AppDir to linuxdeploy.
> 
> I someone has been successful in doing so, I would be glad to add its directives to the documentation, for e.g. as a PR?

please add its tutorial to documentation. thanks
