### ISSUE TITLE
missing multiple shared object libraries

### ISSUE THREAD

**Issue by py-radicz** [niess/python-appimage#83]
is there a chance that latest releases are missing shared libraries? I cant import python ssl module with following import error

ImportError: libssl.so.3: cannot open shared object file: No such file or directory

I did symlinked this from /usr/lib on my host system, then it failed with another ImportError: libcrypto

to be specific I am talking about release manylinux 2014 x86_64 for py3.12.7 - on release py.3.12.3 it worked just fine

**Comment by niess** [comment]
Hello @py-radicz,

thank you for pointing this out. I just produced patched AppImages where the issue should be solved.

Openssl was updated to version 3 in Manylinux 2014 AppImages (for Python 3.8+), likely some time ago, but this was not propagated due to a bug on my side (hopefully patched now).
