### ISSUE TITLE
pip install: option -c not recognized

### ISSUE THREAD

**Issue by anki-code** [niess/python-appimage#9]
Hi! Thank you for python-appimage! It's really help!

I've faced with error when I run `pip install` in `xonsh.AppImage` using `python` from AppImage:
```
# which python                                                                                                                                                                      
/tmp/.mount_xonshxIlqpg/usr/bin/python

# python -m pip install xontrib-schedule 
Collecting xontrib-schedule
  Downloading xontrib-schedule-0.0.1.tar.gz (1.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /root/.xxh/.xxh/shells/xxh-shell-xonsh-appimage/build/xonsh -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vfdplxou/xontrib-schedule/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vfdplxou/xontrib-schedule/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-vfdplxou/xontrib-schedule/pip-egg-info
         cwd: /tmp/pip-install-vfdplxou/xontrib-schedule/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option -c not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I think this appears because:
```
# ls -la /tmp/.mount_xonshP4mlJm/usr/bin/python*                                                                                                                                    
/tmp/.mount_xonshP4mlJm/usr/bin/python -> python3
/tmp/.mount_xonshP4mlJm/usr/bin/python3 -> python3.8
/tmp/.mount_xonshP4mlJm/usr/bin/python3.8
```
Where `python3.8` is a wrapper script over `$APPDIR/opt/python3.8/bin/python3.8`.

Pip install works when I do with binary python:
```
# /tmp/.mount_xonshP4mlJm/opt/python3.8/bin/python3.8 -m pip install xontrib-schedule                                                                                               
Successfully installed xontrib-schedule-0.0.1
```

So the questions is what is the right way to use python from AppImage in $PATH? Before I faced with this issue I did just:
 ```
$PATH = [f'{$APPDIR}/usr/bin'] + $PATH
```
because `usr/bin` has all python symlinks.

(For workaround I'm going to use `$APPDIR/opt/python3.8/bin/python3.8 -m pip` as `pip` alias)

Thanks!

**Comment by niess** [comment]
Hello @anki-code. What surprises me is that the error reports:
```bash
command: /root/.xxh/.xxh/shells/xxh-shell-xonsh-appimage/build/xonsh -c
```
instead of `/tmp/.mount_xonshP4mlJm/usr/bin/python`. Does it also fail if you explicitly call the wrapper, e.g. as:

```
/tmp/.mount_xonshP4mlJm/usr/bin/python -m pip install xontrib-schedule
```
(with the actual `tmp` or maybe '$APPDIR' instead).

**Comment by anki-code** [comment]
> Does it also fail if you explicitly call the wrapper

Yes
```
$ @($APPDIR)/usr/bin/python -m pip install xontrib-schedule                                                 
Defaulting to user installation because normal site-packages is not writeable
Collecting xontrib-schedule
  Downloading xontrib-schedule-0.0.1.tar.gz (1.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/.xxh/.xxh/shells/xxh-shell-xonsh-appimage/build/xonsh -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mvbo4ssg/xontrib-schedule/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mvbo4ssg/xontrib-schedule/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-mvbo4ssg/xontrib-schedule/pip-egg-info
         cwd: /tmp/pip-install-mvbo4ssg/xontrib-schedule/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option -c not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by anki-code** [comment]
If you have linux server with ssh you can test it easy way:
```bash
pip install xxh-xxh
xxh yourserver    # xonsh by default
@($APPDIR)/usr/bin/python -m pip install xontrib-schedule    
```
Don't worry about server environment. The xxh is hermetic and all files and packages will be in `/home/user/.xxh` directory.

**Comment by niess** [comment]
OK, if you run the xonsh AppImage and do the following from the xonsh shell:
```
import sys
sys.argv
['-c']
```
But if I run a Python AppImage I get `['']` for `sys.argv` which is what I also get with my system Python. So now the question, why is the `-c` arg not properly swallowed in the case of xonsh? I'll have a look.

**Comment by niess** [comment]
OK, actually this is usual Python behaviour. For example with my system python (2.7) I got:

```bash
python -c  "import sys; print sys.argv"
['-c']
```

So maybe that xonsh filters out the `-c` arg but it does not work with the wrapper?

I am actually trying to understand where this error comes from:
```bash
error: option -c not recognized
```

**Comment by anki-code** [comment]
May be this stack could help:
1. xxh run appimage (`xonsh` is AppImage):
```
xonsh --no-script-cache -i --rc $CURRENT_DIR/xonshrc.xsh
```
2. https://github.com/niess/python-appimage/blob/master/applications/xonsh/entrypoint.sh
```
{{ python-executable }} -u -c 'from xonsh.main import main; main()' "$@"
```
3. And we have in args:
```
$ import sys 
. sys.argv 
.                                                                                                                 
['-c',
 '--no-script-cache',
 '-i',
 '--rc',
 '/home/ubuntu/.xxh/.xxh/shells/xxh-shell-xonsh-appimage/build/xonshrc.xsh']
```

**Comment by niess** [comment]
And what happens if you change your entry point (`AppRun` last line) to:

```
${APPDIR}/usr/bin/xonsh "$@"
```

Instead of

```
 ${APPDIR}/usr/bin/xonsh "-u" "-c" 'from xonsh.main import main; main()' "$@"
```

One difference is that `argv[0]` is pointing to xonsh in the first case but to `-c` in the second case (which is the usual Python behaviour).

**Comment by anki-code** [comment]
> And what happens if you change your entry point 

The `-c` option has gone:

```
$ import sys 
. sys.argv 
.                                                                                                                 
['/tmp/.mount_xonshmC1umC/usr/bin/xonsh',
 '--no-script-cache',
 '-i',
 '--rc',
 '/home/ubuntu/.xxh/.xxh/shells/xxh-shell-xonsh-appimage/build/xonshrc.xsh']
```
But the error is still here:
```
$ which python                                                                                                    
/tmp/.mount_xonshmC1umC/usr/bin/python

$ python -m pip install xontrib-schedule                                                                          
Defaulting to user installation because normal site-packages is not writeable
Collecting xontrib-schedule
  Using cached xontrib-schedule-0.0.1.tar.gz (1.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/.xxh/.xxh/shells/xxh-shell-xonsh-appimage/build/xonsh -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9j9w1j4k/xontrib-schedule/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9j9w1j4k/xontrib-schedule/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-9j9w1j4k/xontrib-schedule/pip-egg-info
         cwd: /tmp/pip-install-9j9w1j4k/xontrib-schedule/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option -c not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by niess** [comment]
OK, thank you :) So this is not related :( Anyway, its probably cleaner to call the xonsh script in the AppImage. That's closer to what one would have if using the system Python.

**Comment by niess** [comment]
The following works:
```bash
./xonsh-x86_64.AppImage -c '@($APPDIR)/usr/bin/python -m pip install numpy'
```
but not
```
./xonsh-x86_64.AppImage -c '@($APPDIR)/usr/bin/python -m pip install xontrib-schedule'
```

One difference is that `numpy` is installed from a wheel but `xontrib-schedule` from the source. I will try with the Python AppImage.

**Comment by niess** [comment]
Both work with the Python AppImage. I am puzzled now :P

**Comment by anki-code** [comment]
May be it helps:
```
$ python -m pip install --isolated xontrib-schedule 

Defaulting to user installation because normal site-packages is not writeable
Collecting xontrib-schedule
  Using cached xontrib-schedule-0.0.1.tar.gz (1.9 kB)
    ERROR: Command errored out with exit status 2:
     command: /home/ubuntu/.xxh/.xxh/shells/xxh-shell-xonsh-appimage/build/xonsh -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-marzz8xj/xontrib-schedule/setup.py'"'"'; __file__='"'"'/tmp/pip-install-marzz8xj/xontrib-schedule/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base /tmp/pip-install-marzz8xj/xontrib-schedule/pip-egg-info
         cwd: /tmp/pip-install-marzz8xj/xontrib-schedule/
    Complete output (7 lines):
    usage: xonsh [-h] [-V] [-c COMMAND] [-i] [-l] [--config-path CONFIG_PATH]
                 [--rc RC [RC ...]] [--no-rc] [--no-script-cache]
                 [--cache-everything] [-D ITEM]
                 [--shell-type {b,best,d,dumb,ptk,ptk1,ptk2,prompt-toolkit,prompt_toolkit,prompt-toolkit1,prompt-toolkit2,rand,random,rl,readline}]
                 [--timings]
                 [script-file] ...
    xonsh: error: unrecognized arguments: --no-user-cfg
    ----------------------------------------
ERROR: Command errored out with exit status 2: python setup.py egg_info Check the logs for full command output.
```
Here is `unrecognized arguments: --no-user-cfg` and we can findin command section `...  --no-user-cfg egg_info ...`.

**Comment by anki-code** [comment]
And I don't understand why `python -m pip` runs `/home/ubuntu/.xxh/.../build/xonsh -c ...`

**Comment by niess** [comment]
Indeed that could be the problem. For example:

```bash
./xonsh-x86_64.AppImage -c '@($APPDIR)/usr/bin/python -m pip'

Usage:   
  /home/niess/.../xonsh-x86_64.AppImage -m pip <command> [options]
```
but

```bash
./xonsh-x86_64.AppImage -c '@($APPDIR)/opt/python3.8/bin/python3.8 -m pip'

Usage:   
  /tmp/.mount_xonsh-Nyjb7N/opt/python3.8/bin/python3.8 -m pip <command> [options]
```

The python wrapper is faking a call direct from the AppImage (i.e. as if the AppImage was the python exec). This is needed for virtual envs to work properly. But in the case of xonsh it might be problematic because python redirects to the AppImage which actually runs AppRun i.e. xonsh instead of python.

**Comment by niess** [comment]
That could explain that it works with the Python AppImage but not with the Xonsh one. The latter is actually called 2 times in cascade adding one more '-c' to the list of args :(

**Comment by niess** [comment]
Indeed, installing `xontrib-schedule` through Xonsh but using the extracted AppImage works. In this case the wrapper can direct to the original Python since it has a fixed location. But when running from an AppImage I am redirecting to the AppImage itself since this is the only fixed location. However this only works if the AppImage is indeed starting Python.

I have to think more how to solve this problem.

**Comment by anki-code** [comment]
Wow! I've tried 8378957 and it works for me! Great! Many thanks!

**Comment by niess** [comment]
@anki-code Great :)

I introduced a new bug with this commit for extracted images. But now its patched.

Thanks for the coffee :P

I also have some strange glitch which I don't understand. In some situations the xonsh AppImage suspends and I am back to the initial shell with the xonsh process halted in background. Does this also happen to you?

**Comment by anki-code** [comment]
Yep. This is xonsh regression starts with 0.9.14. I described in https://github.com/niess/python-appimage/issues/8#issuecomment-616111604

I think this problem of how xonsh works in AppImage. After 0.9.14 release something breaks in logic on subprocess command and `promt_toolkit` freeze. When you run python commands ('2+2') it works but when you try to run subprocess command (`echo 123`) the xonsh stops and stays in processes.

This regress appears only in AppImage and when I run it from bash. If I run xonsh.AppImage from xonsh the regress not appears. It looks like xonsh in AppImage hasn't some environment, don't know. I'm going to deep dive into it.
